[build]
rustflags = ["-C", "link-arg=-fuse-ld=/nix/store/4m8s1q7pk96cls4wqfg2f9s4kilv7nyi-mold-unwrapped-wrapper-2.40.4/bin/mold"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=/nix/store/4m8s1q7pk96cls4wqfg2f9s4kilv7nyi-mold-unwrapped-wrapper-2.40.4/bin/mold"]
